Repository age-series/ElectricalAge, pull requests merged in 2018-08, with the labels that each got.

#42 added microfarad support
  src/main/java/mods/eln/misc/Utils.java
Labels: bug

#51 changed to 8 lead around a machine part
  src/main/java/mods/eln/Eln.java
Labels: enhancement

#39 some progress
  src/main/java/mods/eln/packets/TransparentNodeResponsePacket.kt
  src/main/java/mods/eln/sixnode/electricalcable/ElectricalSignalBusCableElement.java
Labels: Ready, enhancement

#44 Fixed motors in various ways:
  src/main/java/mods/eln/mechanical/Motor.kt
Labels: Ready
