Repository age-series/ElectricalAge, pull requests merged in 2019-01, with the labels that each got.

#78 added export stuff
  src/main/java/mods/eln/server/ConsoleListener.java
  src/main/java/mods/eln/sim/mna/RootSystem.java
  src/main/java/mods/eln/sim/mna/SubSystem.java
  src/main/java/mods/eln/sim/mna/component/Bipole.java
  src/main/java/mods/eln/sim/mna/component/Component.java
  src/main/java/mods/eln/sim/mna/state/State.java
Labels: enhancement

#83 Make turrets ignore previous invulnerability timer
  src/main/java/mods/eln/transparentnode/turret/TurretSlowProcess.java
Labels: enhancement, ready

#74 Tracking `devel-power-sockets`
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/entity/ReplicatorPopProcess.java
  src/main/java/mods/eln/misc/Utils.java
  src/main/java/mods/eln/node/six/SixNodeElementRender.java
  src/main/java/mods/eln/sim/mna/RootSystem.java
  src/main/java/mods/eln/sixnode/powersocket/PowerSocketContainer.java
  src/main/java/mods/eln/sixnode/powersocket/PowerSocketDescriptor.java
  src/main/java/mods/eln/sixnode/powersocket/PowerSocketElement.java
  src/main/java/mods/eln/sixnode/powersocket/PowerSocketGui.java
  src/main/java/mods/eln/sixnode/powersocket/PowerSocketRender.java
Labels: enhancement, ready

#79 Fork Stuff
  .travis.yml
  CONTRIBUTING.md
  README.md
  build.gradle
  build.sh
  gradle.properties
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/client/VersionCheckerHandler.java
  src/main/java/mods/eln/misc/Version.java
  src/main/java/mods/eln/server/ConsoleListener.java
  src/main/resources/mcmod.info
Labels: enhancement, meta, ready

#87 added crafting for nixies and digital displays
  src/main/java/mods/eln/Eln.java
Labels: enhancement, ready

#89 Data loggers are now colorable
  src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerDescriptor.java
  src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerElement.java
  src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerRender.java
Labels: enhancement, ready

#90 batteries no longer recharge if they can't do that
  src/main/java/mods/eln/sim/BatteryProcess.java
  src/main/java/mods/eln/sim/nbt/NbtBatteryProcess.java
  src/main/java/mods/eln/transparentnode/battery/BatteryElement.java
Labels: bug, ready

#91 converted to 32x32 and moved slightly
  src/main/resources/assets/eln/textures/items/thermalprobechip.png
Labels: bug, ready

#94 That's less horrible. That was exessive
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/client/VersionCheckerHandler.java
Labels: bug, ready

#93 Tracking devel-shaft-objects again
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/mechanical/Clutch.kt
  src/main/java/mods/eln/mechanical/VerticalHub.kt
  src/main/java/mods/eln/misc/Direction.java
  src/main/resources/assets/eln/model/TestCube/Cube.png
  src/main/resources/assets/eln/model/TestCube/TestCube.blend
  src/main/resources/assets/eln/model/TestCube/TestCube.mtl
  src/main/resources/assets/eln/model/TestCube/TestCube.obj
  src/main/resources/assets/eln/model/turbineSteam/VerticalHub.blend
  src/main/resources/assets/eln/model/turbineSteam/VerticalHub.mtl
  src/main/resources/assets/eln/model/turbineSteam/VerticalHub.obj
  src/main/resources/assets/eln/textures/items/coalclutchplate.png
  src/main/resources/assets/eln/textures/items/coalclutchplate.xcf
  src/main/resources/assets/eln/textures/items/copperclutchplate.png
  src/main/resources/assets/eln/textures/items/copperclutchplate.xcf
  src/main/resources/assets/eln/textures/items/goldclutchplate.png
  src/main/resources/assets/eln/textures/items/goldclutchplate.xcf
  src/main/resources/assets/eln/textures/items/ironclutchplate.png
  src/main/resources/assets/eln/textures/items/ironclutchplate.xcf
  src/main/resources/assets/eln/textures/items/leadclutchplate.png
  src/main/resources/assets/eln/textures/items/leadclutchplate.xcf
Labels: enhancement, ready

#81 Added Config Copy Tool.
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/generic/GenericItemBlockUsingDamageDescriptor.java
  src/main/java/mods/eln/generic/GenericItemUsingDamageDescriptor.java
  src/main/java/mods/eln/gridnode/GridElement.kt
  src/main/java/mods/eln/item/ConfigCopyToolDescriptor.java
  src/main/java/mods/eln/item/IConfigurable.java
  src/main/java/mods/eln/item/ItemMovingHelper.java
  src/main/java/mods/eln/mechanical/Tachometer.kt
  src/main/java/mods/eln/misc/Player.kt
  src/main/java/mods/eln/misc/Utils.java
  src/main/java/mods/eln/node/AutoAcceptInventoryProxy.kt
  src/main/java/mods/eln/node/NodeBase.java
  src/main/java/mods/eln/node/six/SixNode.java
  src/main/java/mods/eln/node/transparent/TransparentNode.java
  src/main/java/mods/eln/sixnode/AnalogChips.kt
  src/main/java/mods/eln/sixnode/electricaldatalogger/DataLogs.java
  src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerElement.java
  src/main/java/mods/eln/sixnode/electricaldigitaldisplay/ElectricalDigitalDisplayElement.java
  src/main/java/mods/eln/sixnode/electricalrelay/ElectricalRelayElement.java
  src/main/java/mods/eln/sixnode/electricalsensor/ElectricalSensorElement.java
  src/main/java/mods/eln/sixnode/electricalsource/ElectricalSourceElement.java
  src/main/java/mods/eln/sixnode/lampsocket/LampSocketElement.java
  src/main/java/mods/eln/sixnode/lampsupply/LampSupplyElement.java
  src/main/java/mods/eln/sixnode/powercapacitorsix/PowerCapacitorSixElement.java
  src/main/java/mods/eln/sixnode/powerinductorsix/PowerInductorSixElement.java
  src/main/java/mods/eln/sixnode/thermalsensor/ThermalSensorElement.java
  src/main/java/mods/eln/sixnode/wirelesssignal/rx/WirelessSignalRxElement.java
  src/main/java/mods/eln/sixnode/wirelesssignal/source/WirelessSignalSourceElement.java
  src/main/java/mods/eln/sixnode/wirelesssignal/tx/WirelessSignalTxElement.java
  src/main/java/mods/eln/sound/SoundCommand.java
  src/main/resources/assets/eln/lang/en_US.lang
  src/main/resources/assets/eln/sounds.json
  src/main/resources/assets/eln/sounds/beep_accept.ogg
  src/main/resources/assets/eln/sounds/beep_accept_2.ogg
  src/main/resources/assets/eln/sounds/beep_error.ogg
  src/main/resources/assets/eln/textures/items/configcopytool.png
  src/main/resources/assets/eln/textures/items/configcopytool.xcf
Labels: enhancement, ready

#95 Fixed wire IDs
  gradle.properties
  src/main/java/mods/eln/Eln.java
Labels: bug, ready

#104 More transformer ratios
  src/main/java/mods/eln/transparentnode/transformer/TransformerContainer.java
  src/main/java/mods/eln/transparentnode/transformer/TransformerDescriptor.java
Labels: enhancement, ready

#106 Fixed street lamp rendering in hand
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/sixnode/lampsocket/LampSocketDescriptor.java
Labels: bug, ready
