Repository age-series/ElectricalAge, pull requests merged in 2019-06, with the labels that each got.

#136 various 1.16.x changes
  gradle.properties
  src/main/java/mods/eln/Achievements.java
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/client/AnalyticsHandler.java
  src/main/java/mods/eln/client/VersionCheckerHandler.java
  src/main/java/mods/eln/generic/GenericCreativeTab.java
  src/main/java/mods/eln/gridnode/electricalpole/ElectricalPoleElement.kt
  src/main/java/mods/eln/gridnode/electricalpole/ElectricalPoleRender.kt
  src/main/java/mods/eln/mechanical/Clutch.kt
  src/main/java/mods/eln/mechanical/Flywheel.kt
  src/main/java/mods/eln/mechanical/Generator.kt
  src/main/java/mods/eln/mechanical/Motor.kt
  src/main/java/mods/eln/mechanical/Tachometer.kt
  src/main/java/mods/eln/mechanical/Turbines.kt
  src/main/java/mods/eln/misc/ConfigHandler.java
  src/main/java/mods/eln/misc/Utils.java
  src/main/java/mods/eln/misc/Version.java
  src/main/java/mods/eln/packets/AchievePacketHandler.java
  src/main/java/mods/eln/registry/ItemRegistry.java
  src/main/java/mods/eln/registry/MscRegistry.java
  src/main/java/mods/eln/registry/RegistryUtils.java
  src/main/java/mods/eln/registry/SixNodeRegistry.java
  src/main/java/mods/eln/registry/TransparentNodeRegistry.java
  src/main/java/mods/eln/sim/mna/process/TransformerInterSystemProcess.java
  src/main/java/mods/eln/sixnode/AnalogChips.kt
  src/main/java/mods/eln/sixnode/ElectricalFuse.kt
  src/main/java/mods/eln/sixnode/LogicGate.kt
  src/main/java/mods/eln/sixnode/Scanner.kt
  src/main/java/mods/eln/sixnode/electricalfiredetector/ElectricalFireDetectorRender.kt
  src/main/java/mods/eln/sixnode/electricalmath/ElectricalMathDescriptor.java
  src/main/java/mods/eln/transparentnode/NixieTube.kt
  src/main/java/mods/eln/transparentnode/battery/BatteryDescriptor.java
  src/main/java/mods/eln/transparentnode/electricalmachine/ElectricalMachineDescriptor.java
  src/main/java/mods/eln/transparentnode/transformer/TransformerElement.java
  src/main/resources/assets/eln/model/NixieTube/digit_atlas.png
Labels: bug, enhancement, in progress

#139 fixed variable overlap
  src/main/java/mods/eln/sixnode/electricalcable/ElectricalCableDescriptor.java
Labels: bug

#143 Converted ClientKeyHandler to Kotlin, fixed a bunch of bugs with exis…
  src/main/java/mods/eln/CommonProxy.java
  src/main/java/mods/eln/CommonProxy.kt
  src/main/java/mods/eln/Eln.java
  src/main/java/mods/eln/PacketHandler.java
  src/main/java/mods/eln/client/ClientKeyHandler.java
  src/main/java/mods/eln/client/ClientKeyHandler.kt
  src/main/java/mods/eln/client/ClientProxy.java
  src/main/java/mods/eln/misc/KeyRegistry.kt
Labels: bug, enhancement, refactor

#151 Fix for Issue #141 - Autominer using full chest
  src/main/java/mods/eln/transparentnode/autominer/AutoMinerSlowProcess.java
Labels: bug, enhancement, ready
