Repository age-series/ElectricalAge, pull requests merged in 2019-12, with the labels that each got.

#202 Hotfix vdcdc
  src/main/java/mods/eln/sim/mna/RootSystem.java
  src/main/java/mods/eln/sixnode/electricalcable/ElectricalCableElement.java
  src/main/java/mods/eln/transparentnode/variabledcdc/VariableDcDc.kt
Labels: crash, enhancement, ready

#203 Put a dev-friendly message in the debug log for the next time this happens
  src/main/java/mods/eln/sim/mna/RootSystem.java
Labels: enhancement, ready

#208 hotfix-net: Fixes #206 once and for all
  src/main/java/mods/eln/node/six/SixNodeEntity.java
  src/main/java/mods/eln/sixnode/energymeter/EnergyMeterRender.java
Labels: bug, crash, ready
